language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
gemfile:
  - gemfiles/active_record_30.gemfile
  - gemfiles/active_record_31.gemfile
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/active_record_40.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/active_record_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_30.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_31.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_32.gemfile
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
