language: ruby
script: bundle exec rspec spec
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
gemfile:
  - gemfiles/Gemfile-rails.3.0.x
  - gemfiles/Gemfile-rails.3.1.x
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.3.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.3.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.3.0.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.3.1.x
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile-rails.4.0.x
  allow_failures:
    - rvm: ruby-head
